# Generated by Django 5.1.3 on 2024-11-15 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtobuy',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
